---
- name: "CliXX DB Deployment Ansible Playbook"
  hosts: localhost
  connection: local
  become: ec2-user
  vars:
    instance_id: wordpressdbclixxjenkins
    db_snapshot: wordpressdbclixxsnap
    security_group: sg-071013dfe6470bf59
  tasks:
    - name: Restore DB from snapshot
      community.aws.rds_snapshot:
        db_instance_identifier: "{{ instance_id }}"
        snapshot_id: "{{ db_snapshot }}"
        state: present
        wait: yes
        region: us-east-1
        instance_type: db.t2.small
        wait_timeout: 1200

    - name: Modify to add SG
      community.aws.rds_instance:
        db_instance_identifier: "{{ instance_id }}"
        security_groups: ["{{ security_group }}"]
        region: us-east-1
